/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-02-01 09:30:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<!-- bootstrap -->\r\n");
      out.write("\t\t<link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">      \r\n");
      out.write("\t\t<link href=\"bootstrap/css/bootstrap-responsive.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link href=\"themes/css/bootstrappage.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("<!-- global styles -->\r\n");
      out.write("\t\t<link href=\"themes/css/flexslider.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\t\t<link href=\"themes/css/main.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\r\n");
      out.write("<!-- scripts -->\r\n");
      out.write("\t\t<script src=\"themes/js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"bootstrap/js/bootstrap.min.js\"></script>\t\t\t\t\r\n");
      out.write("\t\t<script src=\"themes/js/superfish.js\"></script>\t\r\n");
      out.write("\t\t<script src=\"themes/js/jquery.scrolltotop.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t  <style type=\"text/css\">\r\n");
      out.write("      \r\n");
      out.write("      *{\r\n");
      out.write("         font-family : 'Nanum Gothic';\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      thead th {\r\n");
      out.write("         background-color : black;\r\n");
      out.write("         color: white;\r\n");
      out.write("      }\r\n");
      out.write("      .form{\r\n");
      out.write("         margin-bottom: 0 px;\r\n");
      out.write("      \r\n");
      out.write("      }\r\n");
      out.write("      .col-md-4{\r\n");
      out.write("      display:table;\r\n");
      out.write("      }\r\n");
      out.write("      </style>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<div id=\"wrapper\" class=\"container\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<section class=\"header_text sub\">\r\n");
      out.write("\t\t\t<img class=\"pageBanner\" src=\"themes/images/pageBanner.png\" alt=\"New products\" >\r\n");
      out.write("\t\t\t\t<h4><span>로그인</span></h4>\r\n");
      out.write("\t\t\t</section>\t\t\t\r\n");
      out.write("\t\t\t<section class=\"main-content\">\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"span4\" style=\"width:27%\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"span5 center\" id=\"loginspan\">\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<form action=\"login_check.mvc\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"next\" value=\"/\">\r\n");
      out.write("\t\t\t\t\t\t\t <table class=\"table table-bordered table-hover\" style=\"text-align:center; border: 1px solid #dddddd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead> \r\n");
      out.write("\t\t\t\t\t\t\t\t <tr>\r\n");
      out.write("                                 <th colspan=\"2\"><h4 class=\"center\">로그인</h4></th>                              \r\n");
      out.write("                              </tr>\r\n");
      out.write("                              </thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"width: 100px;\"><h5>아이디</h5></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\t<input class=\"form-control\" type=\"text\" name=\"id\" placeholder=\"아이디를 입력해주세요\" id=\"username\" class=\"input-xlarge\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\"width: 100px;\"><h5>비밀번호</h5></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input class=\"form-control\" type=\"password\" name=\"pw\" placeholder=\"비밀번호를 입력해주세요\" id=\"password\" class=\"input-xlarge\" required></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"3\" class=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"btn btn-inverse large\" type=\"submit\" value=\"로그인\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"btn btn-inverse large\" type=\"button\" onclick=\"location.href = 'register.jsp'\" value=\"회원가입\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"reset\">혹시 <a tabindex=\"4\" href=\"#\" title=\"Recover your username or password\">아이디 혹은 비밀번호</a>를 잊으셨나요?</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</table> <!-- onKeyUp=\"\" , onKeyDown=\"\" , onKeyPress=\"\" , onClick=\"\" 속성은 스크립트속성 즉 저 \"\" 내부는 스크립트 영역임. 스크립스 영역을 따로 만들어서 함수를 만들고,\r\n");
      out.write("\t\t\t\t\t\t\t\t함수를 호출 할 수도 있겠지만, 간단한 거라면 함수의 내용을 그대로 적어줘도 작동한다.-->\r\n");
      out.write("\t\t\t\t\t\t</form>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"span4\" style=\"width:25%\">\r\n");
      out.write("\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
