/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-01-30 02:37:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class product_005finsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<!-- bootstrap -->\r\n");
      out.write("\t\t<link href=\"bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">      \r\n");
      out.write("\t\t<link href=\"bootstrap/css/bootstrap-responsive.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link href=\"themes/css/bootstrappage.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("<!-- global styles -->\r\n");
      out.write("\t\t<link href=\"themes/css/flexslider.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\t\t<link href=\"themes/css/main.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\r\n");
      out.write("<!-- scripts -->\r\n");
      out.write("\t\t<script src=\"themes/js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"bootstrap/js/bootstrap.min.js\"></script>\t\t\t\t\r\n");
      out.write("\t\t<script src=\"themes/js/superfish.js\"></script>\t\r\n");
      out.write("\t\t<script src=\"themes/js/jquery.scrolltotop.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function postAction(){\r\n");
      out.write("\tvar title = document.getElementById(\"title\");\r\n");
      out.write("\tvar code = document.getElementById(\"code\");\r\n");
      out.write("\tvar price = document.getElementById(\"price\");\r\n");
      out.write("\tvar upForm =document.getElementById('upForm');\r\n");
      out.write("\tvar input = document.createElement(\"input\");\r\n");
      out.write("\t\r\n");
      out.write("\tif(title.value == \"\"){\r\n");
      out.write("\t\talert(\"상품 제목을 입력해주세요\");\r\n");
      out.write("\t\ttitle.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(code.value == \"\"){\r\n");
      out.write("\t\talert(\"상품 코드를 입력해주세요\");\r\n");
      out.write("\t\tcode.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(price.value == \"\"){\r\n");
      out.write("\t\talert(\"상품 가격를 입력해주세요\");\r\n");
      out.write("\t\tprice.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput.type = \"hidden\";\r\n");
      out.write("\tinput.name = \"flag\";\r\n");
      out.write("\tinput.value = \"postWrite\";\r\n");
      out.write("\tupForm.appendChild(input);\r\n");
      out.write("\t\r\n");
      out.write("\tupForm.submit();\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"wrapper\" class=\"container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<section class=\"header_text sub\">\r\n");
      out.write("\t\t\t<h1><h3>상품등록</h3></h1>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<form id=\"upForm\" action=\"upload.mvc\" method=\"post\" enctype=\"multipart/form-data\"> <!-- 폼 태그 시작점 -->\r\n");
      out.write("\t\t\t<section class=\"main-content\">\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"row\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"span9\" style=\"margin: 15%; margin-bottom: 1%; margin-top: 1%;\"> <!-- 씨바 얘네좀 가운데로 보내줘 ㅠㅠㅠㅠㅠㅠㅠㅠㅠ  -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"span4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- \t\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"thumbnail_insert\" data-fancybox-group=\"group1\" title=\"Description 1\"><img alt=\"\" src=\"./themes/images/\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"thumbnails small\">\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"span1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"thumbnail_insert\" data-fancybox-group=\"group1\" title=\"Description 2\"><img src=\"./themes/images/\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"span1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"thumbnail_insert\" data-fancybox-group=\"group1\" title=\"Description 3\"><img src=\"./themes/images/\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"span1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"thumbnail_insert\" data-fancybox-group=\"group1\" title=\"Description 4\"><img src=\"./themes/images/\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t메인 이미지 파일(file):<input type=\"file\" name=\"main_image\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t서브 이미지 파일1(file):<input type=\"file\" name=\"image1\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t서브 이미지 파일2(file):<input type=\"file\" name=\"image2\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t서브 이미지 파일3(file):<input type=\"file\" name=\"image3\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"span5\" style=\"margin_left:100px\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4><strong>상품명: </strong></h4> <input id=\"title\" type=\"text\" name=\"item_title\" ><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<address>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>카테고리_1: </strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select name=\"main_cate\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>men</option> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>woman</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>boy</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>girl</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>카테고리_2: </strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select name=\"sub_cate\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>top</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>bottom</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option>acc</option>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>상품코드:</strong> <input id=\"code\" type=\"text\" name=\"item_code\" ><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<strong>사이즈:</strong> <br>  <!-- 체크되면 뒤에 인풋 활성화 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>S </strong>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>수량:</strong> <input type=\"number\" name=\"s_size\" style=\"width:50px\" max=\"500\" value=\"0\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>M </strong>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>수량:</strong> <input type=\"number\" name=\"m_size\" style=\"width:50px\" max=\"500\" value=\"0\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>L </strong>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>수량:</strong> <input type=\"number\" name=\"l_size\" style=\"width:50px\" max=\"500\" value=\"0\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>XL </strong>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>수량:</strong> <input type=\"number\" name=\"xl_size\" style=\"width:50px\" max=\"500\" value=\"0\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</address>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<strong>가격:</strong><input id=\"price\" type=\"number\" name=\"price\" style=\"width:120px\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"span9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tab-pane active\" id=\"home\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t본문 이미지<br><input type=\"file\" name=\"content_image\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t추가내용<br>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea style=\"width:80%; height:100px;\" name=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</textarea>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"span9\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"pull-left\"><span class=\"text\"><strong>관련 추천</strong>상품</span></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"left button\" href=\"#myCarousel-1\" data-slide=\"prev\"></a><a class=\"right button\" href=\"#myCarousel-1\" data-slide=\"next\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"myCarousel-1\" class=\"carousel slide\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"active item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"thumbnails listing-products\">\t<!-- 관련상품은 팝업창을 띄워서 선택하는걸로 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"span3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"product-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"sale_tag\"></span>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product_detail.jsp\"><img alt=\"\" src=\"themes/images/ladies/6.jpg\"></a><br/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product_detail.jsp\" class=\"title\">Wuam ultrices rutrum</a><br/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"category\">Suspendisse aliquet</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"price\">$341</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"span3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"product-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"sale_tag\"></span>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product_detail.jsp\"><img alt=\"\" src=\"themes/images/ladies/5.jpg\"></a><br/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product_detail.jsp\" class=\"title\">Fusce id molestie massa</a><br/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"category\">Phasellus consequat</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"price\">$341</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>       \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"span3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"product-box\">\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product_detail.jsp\"><img alt=\"\" src=\"themes/images/ladies/4.jpg\"></a><br/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product_detail.jsp\" class=\"title\">Praesent tempor sem</a><br/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"category\">Erat gravida</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"price\">$28</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"thumbnails listing-products\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"span3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"product-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"sale_tag\"></span>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product_detail.jsp\"><img alt=\"\" src=\"themes/images/ladies/1.jpg\"></a><br/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product_detail.jsp\" class=\"title\">Fusce id molestie massa</a><br/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"category\">Phasellus consequat</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"price\">$341</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>       \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"span3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"product-box\">\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product_detail.jsp\"><img alt=\"\" src=\"themes/images/ladies/2.jpg\"></a><br/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product_detail.jsp\">Praesent tempor sem</a><br/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"category\">Erat gravida</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"price\">$28</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"span3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"product-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"sale_tag\"></span>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product_detail.jsp\"><img alt=\"\" src=\"themes/images/ladies/3.jpg\"></a><br/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product_detail.jsp\" class=\"title\">Wuam ultrices rutrum</a><br/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"category\">Suspendisse aliquet</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"price\">$341</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-3\" style=\"text-align:center;\">\r\n");
      out.write("\r\n");
      out.write("    \t\t\t<button class=\"btn btn-inverse\" style=\"width:80px;height:40px;\" onclick=\"postAction();\">등록</a></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</form><!-- 폼태그 끝 -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script src=\"themes/js/common.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
